FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS base
USER app
WORKDIR /app

EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
# ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["./WebApi", "WebApi/"]
RUN dotnet restore "./WebApi/WebApi.csproj"

WORKDIR "/src/WebApi"
RUN dotnet build "./WebApi.csproj" -c Release -o /app/build

FROM build AS publish
##RUN dotnet publish Ditto/Ditto.csproj --runtime linux-musl-x64 -c $BUILDCONFIG -o out /p:Version=$VERSION -p:PublishTrimmed=true

RUN dotnet publish "./WebApi.csproj" -c Release --self-contained true -o /app/publish

#docker pull mcr.microsoft.com/dotnet/runtime-deps:8.0-alpine

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WebApi.dll"]
