FROM mcr.microsoft.com/dotnet/runtime-deps:8.0-alpine AS base
USER app
WORKDIR /app

EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
# ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["./TestWebApiNet8Docker", "TestWebApiNet8Docker/"]
RUN dotnet restore "./TestWebApiNet8Docker/TestWebApiNet8Docker.csproj"

WORKDIR "/src/TestWebApiNet8Docker"
RUN dotnet build "./TestWebApiNet8Docker.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish ./TestWebApiNet8Docker.csproj --runtime linux-musl-x64 --self-contained true -c Release -o /app/publish 
#-p:PublishTrimmed=true


FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["./TestWebApiNet8Docker"]
