
FROM mcr.microsoft.com/dotnet/runtime:8.0 AS base
USER app
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
# ARG BUILD_CONFIGURATION=Release
WORKDIR /src

COPY Worker ./Worker

RUN dotnet restore "./Worker/Worker.csproj"

WORKDIR "/src/Worker"
RUN dotnet build "./Worker.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "./Worker.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Worker.dll"]