FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
# ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["./TestWebApiNet8Docker", "TestWebApiNet8Docker/"]
RUN dotnet restore "./TestWebApiNet8Docker/TestWebApiNet8Docker.csproj"

WORKDIR "/src/TestWebApiNet8Docker"
RUN dotnet build "./TestWebApiNet8Docker.csproj" -c Release -o /app/build

FROM build AS publish
##RUN dotnet publish Ditto/Ditto.csproj --runtime linux-musl-x64 -c $BUILDCONFIG -o out /p:Version=$VERSION -p:PublishTrimmed=true

RUN dotnet publish "./TestWebApiNet8Docker.csproj" -c Release --self-contained true -o /app/publish

EXPOSE 8080
EXPOSE 8081

#docker pull mcr.microsoft.com/dotnet/runtime-deps:8.0-alpine

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TestWebApiNet8Docker.dll"]
